scenario_builder:
  _target_: nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_builder.NuPlanScenarioBuilder
  _convert_: all
  vehicle_parameters:
    _target_: nuplan.common.actor_state.vehicle_parameters.VehicleParameters
    _convert_: all
    width: 2.297
    front_length: 4.049
    rear_length: 1.127
    cog_position_from_rear_axle: 1.67
    height: 1.777
    wheel_base: 3.089
    vehicle_name: pacifica
    vehicle_type: gen1
  scenario_mapping:
    _target_: nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_utils.ScenarioMapping
    _convert_: all
    subsample_ratio_override: 0.5
    scenario_map:
      accelerating_at_crosswalk:
      - 9.0
      - 0.0
      accelerating_at_stop_sign:
      - 9.0
      - 0.0
      accelerating_at_stop_sign_no_crosswalk:
      - 9.0
      - 0.0
      accelerating_at_traffic_light:
      - 9.0
      - 0.0
      accelerating_at_traffic_light_with_lead:
      - 9.0
      - 0.0
      accelerating_at_traffic_light_without_lead:
      - 9.0
      - 0.0
      behind_bike:
      - 9.0
      - 0.0
      behind_long_vehicle:
      - 9.0
      - 0.0
      behind_pedestrian_on_driveable:
      - 9.0
      - 0.0
      behind_pedestrian_on_pickup_dropoff:
      - 9.0
      - 0.0
      changing_lane:
      - 9.0
      - 0.0
      changing_lane_to_left:
      - 9.0
      - 0.0
      changing_lane_to_right:
      - 9.0
      - 0.0
      changing_lane_with_lead:
      - 9.0
      - 0.0
      changing_lane_with_trail:
      - 9.0
      - 0.0
      crossed_by_bike:
      - 9.0
      - 0.0
      crossed_by_vehicle:
      - 9.0
      - 0.0
      following_lane_with_lead:
      - 9.0
      - 0.0
      following_lane_with_slow_lead:
      - 9.0
      - 0.0
      following_lane_without_lead:
      - 9.0
      - 0.0
      high_lateral_acceleration:
      - 9.0
      - 0.0
      high_magnitude_jerk:
      - 9.0
      - 0.0
      high_magnitude_speed:
      - 9.0
      - 0.0
      low_magnitude_speed:
      - 9.0
      - 0.0
      medium_magnitude_speed:
      - 9.0
      - 0.0
      near_barrier_on_driveable:
      - 9.0
      - 0.0
      near_construction_zone_sign:
      - 9.0
      - 0.0
      near_high_speed_vehicle:
      - 9.0
      - 0.0
      near_long_vehicle:
      - 9.0
      - 0.0
      near_multiple_bikes:
      - 9.0
      - 0.0
      near_multiple_pedestrians:
      - 9.0
      - 0.0
      near_multiple_vehicles:
      - 9.0
      - 0.0
      near_pedestrian_at_pickup_dropoff:
      - 9.0
      - 0.0
      near_pedestrian_on_crosswalk:
      - 9.0
      - 0.0
      near_pedestrian_on_crosswalk_with_ego:
      - 9.0
      - 0.0
      near_trafficcone_on_driveable:
      - 9.0
      - 0.0
      on_all_way_stop_intersection:
      - 9.0
      - 0.0
      on_carpark:
      - 9.0
      - 0.0
      on_intersection:
      - 9.0
      - 0.0
      on_pickup_dropoff:
      - 9.0
      - 0.0
      on_stopline_crosswalk:
      - 9.0
      - 0.0
      on_stopline_stop_sign:
      - 9.0
      - 0.0
      on_stopline_traffic_light:
      - 9.0
      - 0.0
      on_traffic_light_intersection:
      - 9.0
      - 0.0
      starting_high_speed_turn:
      - 9.0
      - 0.0
      starting_left_turn:
      - 9.0
      - 0.0
      starting_low_speed_turn:
      - 9.0
      - 0.0
      starting_protected_cross_turn:
      - 9.0
      - 0.0
      starting_protected_noncross_turn:
      - 9.0
      - 0.0
      starting_right_turn:
      - 9.0
      - 0.0
      starting_straight_stop_sign_intersection_traversal:
      - 9.0
      - 0.0
      starting_straight_traffic_light_intersection_traversal:
      - 9.0
      - 0.0
      starting_u_turn:
      - 9.0
      - 0.0
      starting_unprotected_cross_turn:
      - 9.0
      - 0.0
      starting_unprotected_noncross_turn:
      - 9.0
      - 0.0
      stationary:
      - 9.0
      - 0.0
      stationary_at_crosswalk:
      - 9.0
      - 0.0
      stationary_at_traffic_light_with_lead:
      - 9.0
      - 0.0
      stationary_at_traffic_light_without_lead:
      - 9.0
      - 0.0
      stationary_in_traffic:
      - 9.0
      - 0.0
      stopping_at_crosswalk:
      - 9.0
      - 0.0
      stopping_at_stop_sign_no_crosswalk:
      - 9.0
      - 0.0
      stopping_at_stop_sign_with_lead:
      - 9.0
      - 0.0
      stopping_at_stop_sign_without_lead:
      - 9.0
      - 0.0
      stopping_at_traffic_light_with_lead:
      - 9.0
      - 0.0
      stopping_at_traffic_light_without_lead:
      - 9.0
      - 0.0
      stopping_with_lead:
      - 9.0
      - 0.0
      traversing_crosswalk:
      - 9.0
      - 0.0
      traversing_intersection:
      - 9.0
      - 0.0
      traversing_narrow_lane:
      - 9.0
      - 0.0
      traversing_pickup_dropoff:
      - 9.0
      - 0.0
      traversing_traffic_light_intersection:
      - 9.0
      - 0.0
      waiting_for_pedestrian_to_cross:
      - 9.0
      - 0.0
      unknown:
      - 9.0
      - 0.0
  data_root: null
  map_root: null
  sensor_root: null
  db_files: null
  map_version: nuplan-maps-v1.0
  include_cameras: false
  max_workers: null
  verbose: false
scenario_filter:
  _target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
  _convert_: all
  scenario_types: null
  scenario_tokens: null
  log_names:
  - 2021.06.11.12.06.26_veh-35_03726_03971
  - 2021.06.11.12.09.55_veh-16_00104_00221
  - 2021.09.02.02.33.00_veh-51_00276_00365
  - 2021.10.22.18.02.31_veh-28_01717_02099
  - 2021.10.22.18.45.52_veh-28_01175_01298
  map_names: null
  num_scenarios_per_type: null
  limit_total_scenarios: null
  timestamp_threshold_s: 15
  ego_displacement_minimum_m: null
  ego_start_speed_threshold: null
  ego_stop_speed_threshold: null
  speed_noise_tolerance: null
  expand_scenarios: false
  remove_invalid_goals: false
  shuffle: false
model:
  _target_: nuplan_extent.planning.training.modeling.models.nexus.Nexus
  _convert_: all
  diffuser:
    _target_: nuplan_extent.planning.training.modeling.models.diffusion.scenediffusion.simpleDiffusion
    _convert_: all
    pred_param: v
    schedule: shifted_cosine
    steps: 32
    model:
      _target_: nuplan_extent.planning.training.modeling.models.diffusion.models.diffusion.Nexus
      _convert_: all
      nblocks: 4
      hidden_dim: 256
      scene_tensor_dim: 8
  global_encoder:
    _target_: nuplan_extent.planning.training.modeling.models.encoders.perciever_context_encoder.PercieverEncoder
    _convert_: all
    num_latents: 128
    latent_dim: 256
    input_dim: 7
    num_blocks: 2
  render:
    _target_: nuplan_extent.planning.training.modeling.models.renders.gump_render.GUMPRender
    _convert_: all
  postprocessor:
    _target_: nuplan_extent.planning.training.modeling.models.post_processors.gump_naive_planner.GUMPNaivePlanner
    _convert_: all
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: all
    num_poses: 8
    time_horizon: 4.0
  feature_builders:
  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.nexus_feature_builder.NexusFeatureBuilder
    _convert_: all
    agent_features:
    - VEHICLE
    - PEDESTRIAN
    - BICYCLE
    radius: 100.0
    longitudinal_offset: 0.0
    past_time_horizon: 2.0
    past_num_steps: 4
    future_time_horizon: 8.0
    future_num_steps: 16
    num_max_agents:
    - 128
    - 64
    - 32
    map_features:
    - LANE
    - LANE_CONNECTOR
    - STOP_LINE
    - CROSSWALK
    map_num_points_polylines: 21
    map_dim_points_polyline: 7
    map_num_max_polylines: 128
  target_builders:
  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.ego_trajectory_with_past_target_builder.EgoTrajectoryWithPastTargetBuilder
    _convert_: all
    future_trajectory_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: all
      num_poses: 8
      time_horizon: 4.0
  num_paralell_scenario: 1
  downstream_task: scenario_extrapolation
worker:
  _target_: nuplan.planning.utils.multithreading.worker_parallel.SingleMachineParallelExecutor
  _convert_: all
  use_process_pool: true
  max_workers: 36
checkpoint: null
